# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: About
  description: About section
  icon: fingerprint
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  preheading: ""
  heading: ""
  subheading: ""
  content:
    - paragraph: ""
  background_image: ""
  link:
    text: ""
    url: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  preheading: What we are
  heading: We are dynamic team of creative people
  subheading: We are Perfect Solution
  content: 
    - paragraph: "We provide consulting services in the area of IFRS and management reporting."
    - paragraph: "We optimize business processes, making them easier."
  background_image: /images/about/home-8.jpg
  link:
    text: Get started
    url: "#"

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
